### ISSUE TITLE
the trait `Clone` is not implemented for `RequestHook`

### ISSUE THREAD

**Issue by rj76** [eisberg-labs/actix-request-hook#1]
Hi,

I'm trying to implement this for actix-web = "4.1.0" and it errors with:

"the trait `Clone` is not implemented for `RequestHook`"

Is this something that could be fixed?

cheers!

**Comment by amarjanica** [comment]
Hi, thanks for reporting, I'm not sure right now, I'll have to take a look.
I can't remember why I didn't include a Clone derive for `RequestHook`, because `Inner` is Cloneable.
If you add `#[derive(Clone)]` on `RequestHook`, does it work?
If it does, open a PR, and I'll publish a new version.

**Comment by rj76** [comment]
Sorry, my bad. I created the request_hook outside the move. All works as expected.

Closing this :)
